name: Compute and publish AM diffs

on:
  workflow_dispatch:

jobs:
  compute_am_diffs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r am_diffs/requirements.txt
      - name: Compute and publish AM diffs
        env:
          LEGIFRANCE_CLIENT_ID: ${{ secrets.LEGIFRANCE_CLIENT_ID }}
          LEGIFRANCE_CLIENT_SECRET: ${{ secrets.LEGIFRANCE_CLIENT_SECRET }}
          SLACK_AM_CHANNEL: ${{ secrets.SLACK_AM_CHANNEL }}
          PYTHONPATH: "."
        run: |
          python3 am_diffs/compute_am_diffs.py
