name: Compute and publish AM diffs

on:
  workflow_dispatch:
  schedule:
    # <minute [0,59]> <hour [0,23]> <day of the month [1,31]> <month of the year [1,12]> <day of the week [0,6]>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron: "0 0 * * *"

jobs:
  compute_am_diffs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r am_diffs/requirements.txt
      - name: Compute and publish AM diffs
        env:
          LEGIFRANCE_CLIENT_ID: ${{ secrets.LEGIFRANCE_CLIENT_ID }}
          LEGIFRANCE_CLIENT_SECRET: ${{ secrets.LEGIFRANCE_CLIENT_SECRET }}
          SLACK_AM_CHANNEL: ${{ secrets.SLACK_AM_CHANNEL }}
        run: |
          python3 am_diffs/compute_am_diffs.py
